#!/bin/sh

endswith() {
    haystack=$1
    needle=$2

    case "$haystack" in
        *"$needle") true;;
        *) false;;
    esac
}

pkgname=$(echo "$1" | awk -F '/' '{print $(NF)}')

if endswith "$pkgname" ".git"; then
    pkgname=${pkgname%.git}
fi

git submodule add --name "$pkgname" "$1" "common/link/.config/nvim/pack/bundle/opt/$pkgname"
