#!/bin/sh

runperm() {
    echo "I want to run -> $@"
    printf "Are you sure? [y/n] "
    read -r ans

    [ "$ans" = "y" ] && "$@"
}

common() {
    echo "Running common setup"

    mkdir -p ~/.config
    mkdir -p ~/.local/bin

    stow -v -R -t "$HOME" -d "$HOME/dotfiles/common" link
}

macos() {
    echo "I want to run -> curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash"
    printf "Are you sure? [y/n] "
    read -r ans

    if [ "$ans" = "y" ]
    then
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
    else
        echo "skipping homebrew installation"
    fi

    # links
    mkdir -p ~/.config/karabiner
    stow -v -R -t "$HOME" -d "$HOME/dotfiles/macos" link

    # us-altgr-intl for macos
    sudo -k mkdir -p "/Library/Keyboard Layouts"
    kbpath="$PWD/macos/kblayout/us-intl-altgr-dead.bundle"

    sudo -k cp -r "$kbpath" "/Library/Keyboard Layouts/"
    echo "keyboard okidoki"

    # defaults
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock mru-spaces -bool false
    defaults write -g InitialKeyRepeat -int 20
    defaults write -g KeyRepeat -int 2
    defaults write com.apple.finder ShowPathbar -int 1

    defaults write com.apple.menuextra.clock "DateFormat" -string "EEE d MMM  HH:mm"

    killall Dock
    echo "dock okidoki"

    # terminfo
    mkdir -p ~/.terminfo
    for file in "$HOME/dotfiles/macos/terminfo"/*.terminfo
    do
        tic -x -o ~/.terminfo "$file"
    done
    echo "terminfo okidoki"

    # brewfile should go here sometime
}

archlinux() {
    # first install deps
    doas pacman -S rustup stow wget tar

    # run common hooks
    common

    # move bash files if present
    mkdir -p /tmp/ach-install
    [ ! -L "$HOME/.bashrc" ] && mv "$HOME/.bashrc" /tmp/ach-install/.bashrc
    [ ! -L "$HOME/.bash_profile" ] && mv "$HOME/.bash_profile" /tmp/ach-install/.bash_profile
    [ ! -L "$HOME/.bash_logout" ] && mv "$HOME/.bash_logout" /tmp/ach-install/.bash_logout

    echo "check /tmp/ach-install for backed up bash files if needed"

    stow -v -R -t "$HOME" -d "$HOME/dotfiles/arch" link

    # need rust to build paru
    rustup default stable

    wget "https://aur.archlinux.org/cgit/aur.git/snapshot/paru.tar.gz" -O /tmp/paru.tar.gz
    sh -c "cd /tmp && tar zxvf paru.tar.gz && cd /tmp/paru && makepkg -si"

    echo "paru installed"
}

sysname=$(uname)
if [ "$sysname" = "Linux" ]
then
    echo Installing archlinux module
    archlinux
fi

if [ "$sysname" = "Darwin" ]
then
    echo Installing macOS module
    macos
fi
