#!/bin/sh

# xdg-desktop-portals in river
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

killall kanshi 2> /dev/null; kanshi &
killall waybar 2> /dev/null; waybar &

riverctl map normal Super Tab focus-previous-tags
riverctl map normal Alt Tab focus-previous-tags

# Super+Q to close the focused view
riverctl map normal Super Q close
riverctl map normal Super+Shift Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

riverctl map normal Super+Shift R spawn ~/.config/river/init

riverctl map normal Super P spawn bemenu-run

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous


# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Shift+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom
riverctl map normal Super Return spawn foot

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# mod + {d,i}??
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))

    riverctl map normal Super "$i" set-focused-tags $tags
    riverctl map normal Super+Shift "$i" set-view-tags $tags
    riverctl map normal Super+Control "$i" toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioLowerVolume spawn "ach-volume -10% && ach-volume-notify"
    riverctl map $mode None XF86AudioRaiseVolume spawn "ach-volume +10% && ach-volume-notify"
    riverctl map $mode None XF86AudioMute spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"
    riverctl map $mode None XF86AudioPlay spawn "playerctl --player=spotify,mpd,%any play-pause"
    riverctl map $mode None XF86AudioNext spawn "playerctl --player=spotify,mpd,%any next"
    riverctl map $mode None XF86AudioPrev spawn "playerctl --player=spotify,mpd,%any previous"

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Keyboard
riverctl set-repeat 50 300
riverctl keyboard-layout -variant altgr-intl us

# riverctl float-filter-add app-id 'firefox' title 'Sharing Indicator'
# riverctl float-filter-add app-id 'firefox' title 'Picture-in-Picture'

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add csd -app-id "bar"

# Floating rules
# riverctl rule-add float -app-id 'firefox' -title="^Picture-in-Picture$" floating enable, sticky enable, border none

# riverctl rule-add float -app-id 'float*' -title 'foo'
riverctl rule-add float -app-id 'firefox' -title 'Picture-in-Picture'
riverctl rule-add float -app-id 'firefox' -title 'Firefox - Sharing Indicator'
riverctl rule-add float -app-id 'firefox' -title 'Firefox — Sharing Indicator'
riverctl rule-add float -app-id 'pcmanfm'
riverctl rule-add float -app-id 'pavucontrol'
riverctl rule-add float -app-id 'mpv'
riverctl rule-add float -app-id 'imv'
riverctl rule-add ssd   -app-id firefox
# riverctl rule-add float -app-id 'flameshot' floating enable, fullscreen disable, move absolute position 0 0, border pixel 0

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 0 &
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ needs to eliminate gaps (preferrably in a smart manner)
