#!/bin/bash 

case $BUTTON in 
    1) pamixer --toggle-mute ;;
    4) pamixer -i 1 ;;
    5) pamixer -d 1 ;;
esac

vol="$(pamixer --get-volume)"

[ $(pamixer --get-mute) = true ] && echo "🔇 muted" && exit

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "${icon} ${vol}%"
