#!/bin/sh

capslock=$(xset q | grep "Caps Lock:" | awk '{print $4}')
layout=$(setxkbmap -query | awk '/layout/ {print $2}')
variant=$(setxkbmap -query | awk '/variant/ {print $2}')

printf "⌨️ "
if [ "$capslock" = "on" ]; then
    echo "CAPS LOCK"
else
    echo "$layout:$variant"
fi
