#!/bin/sh

icon() {
    printf "^c#f38ba8^%s^d^" "$1"
}

text() {
    echo "$1"
}

barformat() {
    echo "$(icon "󰂰") $(text "$1")"
}

toggle_sink() {
    card=$(pactl list cards | awk -v RS= '/device.alias = "Bose AE2 SoundLink"/ {print $0}')
    card_name=$(echo "$card" | awk -F "Name: " '/Name: / {print $2}')
    card_profile=$(echo "$card" | awk -F "Active Profile: " '/Active Profile: / {print $2}')

    case "$card_profile" in
        "a2dp-sink-sbc_xq")
            pactl set-card-profile "$card_name" headset-head-unit-msbc
            barformat "HSP/HFP mSBC"
            exit
            ;;
        *)
            pactl set-card-profile "$card_name" a2dp-sink-sbc_xq
            barformat "A2DP SBC-XQ"
            exit
            ;;
    esac
}

case $BLOCK_BUTTON in
    1) toggle_sink ;;
esac

case $(pactl get-default-sink) in
    "bluez_output".*)
        card=$(pactl list cards | awk -v RS= '/device.alias = "Bose AE2 SoundLink"/ {print $0}')
        card_name=$(echo "$card" | awk -F "Name: " '/Name: / {print $2}')
        card_profile=$(echo "$card" | awk -F "Active Profile: " '/Active Profile: / {print $2}')

        case "$card_profile" in
            "a2dp-sink")
                barformat "A2DP";;
            "headset-head-unit")
                barformat "HSP/HFP";;
            "a2dp-sink-sbc")
                barformat "A2DP SBC";;
            "a2dp-sink-sbc_xq")
                barformat "A2DP SBC-XQ";;
            "headset-head-unit-cvsd")
                barformat "HSP/HFP CVSD";;
            "headset-head-unit-msbc")
                barformat "HSP/HFP mSBC";;
        esac
        ;;
    *)
        echo "$(icon "󰟎") $(text "No headphones")"
        ;;
esac

