#!/bin/sh

icon() {
    printf "^c#94e2d5^%s^d^" "$1"
}

case $BLOCK_BUTTON in 
    1) pamixer --toggle-mute ;;
    4) pamixer -i 1 ;;
    5) pamixer -d 1 ;;
esac

vol="$(pamixer --get-volume)"

if [ "$(pamixer --get-mute)" = "true" ] || [ "$vol" = "0" ]; then
    vol="^c#45475a^muted^d^"
    echo "$(icon 󰖁) $vol"
elif [ "$vol" -le "30" ]; then
    echo "$(icon 󰕿) $vol%"
elif [ "$vol" -le "70" ]; then
    echo "$(icon 󰖀) $vol%"
else
    echo "$(icon 󰕾) $vol%"
fi
