#!/bin/sh

# this is basic and needed for ls
list() {
    os=$(uname)

    case $os in
        "Darwin") ls -G "$@" ;;
        "Linux") ls --color=auto "$@" ;;
        *) ls "$@" ;;
    esac
}

lfcd() {
    tmp="$(mktemp)"
    lf-ueberzug -last-dir-path="$tmp" "$@"

    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir" || exit
            fi
        fi
    fi
}

# one letters
alias l='list -lhF'
alias p='pnpm'
alias v='nvim'
alias k='kubectl'

# vim redefs
alias vi='nvim'
alias vim='nvim'
alias vgs='nvim -c ":Neogit"'

# TUI shortcuts
alias lf="lfcd"

# SSH. I've been suffering with this lately
alias ssh='TERM=xterm-256color ssh'

alias igrep='grep -i'

# Navigation
# This uses the "list" function defined above that determines if we should use
# --color=auto or -G depending on Linux/Darwin. Could probably be used for BSD
# but since I don't use that, I'm not gonna worry about it
alias ls='list'
alias la='list -alhF'
alias ..='cd ..'

# git and any vc commands
alias groot='cd $(git rev-parse --show-toplevel)'
alias glog='git log --pretty=oneline --abbrev-commit'
alias ga='git add'
alias gaa='git add -A'

# configs
alias dotfiles='cd ~/dotfiles'
alias forks='cd ~/forks'

# reloads
alias so='source ~/.zshrc'

# Node
alias nls='npm list --depth=0'
alias nrt='npm run test -- '
alias nrd='npm run dev -- '

# conflict in a hurry
alias gitconflicts="git diff --name-status --diff-filter=U"
alias gresolve="git diff --name-status --diff-filter=U | awk '{print \$2}' | xargs nvim"

# vim:ft=sh
