name: Shell files pipeline

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v1.0.0
        with:
          aqua_version: v1.17.0
      - name: Set up aqua
        run: |
          aqua init
          aqua g -i koalaman/shellcheck
          aqua i
      - name: Run shellcheck
        run: |
          ./shcheck.sh
